"""add settings and fix notification schema

Revision ID: 2d8b16f44918
Revises: 434f803f4a83
Create Date: 2026-07-28 17:04:27.712784

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d8b16f44918'
down_revision = '434f803f4a83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('company_email', sa.String(length=120), nullable=False),
    sa.Column('company_phone', sa.String(length=30), nullable=False),
    sa.Column('company_address', sa.Text(), nullable=False),
    sa.Column('company_website', sa.String(length=255), nullable=True),
    sa.Column('company_logo', sa.String(length=255), nullable=True),
    sa.Column('default_interview_duration', sa.Integer(), nullable=True),
    sa.Column('ai_score_threshold', sa.Integer(), nullable=True),
    sa.Column('auto_send_email', sa.Boolean(), nullable=True),
    sa.Column('auto_generate_offer', sa.Boolean(), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('setting_id')
    )
    with op.batch_alter_table('job_match', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('recipient_role', sa.String(length=50), nullable=True))
        batch_op.drop_constraint(batch_op.f('notifications_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('notifications_ibfk_1'), 'users', ['user_id'], ['user_id'])
        batch_op.drop_column('recipient_role')
        batch_op.drop_column('notification_type')

    with op.batch_alter_table('job_match', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    op.drop_table('settings')
    # ### end Alembic commands ###
