"""Interview AI Update

Revision ID: 434f803f4a83
Revises: 643329e82cd9
Create Date: 2026-07-26 22:22:34.374593

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '434f803f4a83'
down_revision = '643329e82cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hr_questions', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('technical_questions', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('coding_questions', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('scenario_questions', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('behavioral_questions', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('evaluation', sa.Text(), nullable=False))
        batch_op.drop_column('questions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questions', mysql.TEXT(), nullable=False))
        batch_op.drop_column('evaluation')
        batch_op.drop_column('behavioral_questions')
        batch_op.drop_column('scenario_questions')
        batch_op.drop_column('coding_questions')
        batch_op.drop_column('technical_questions')
        batch_op.drop_column('hr_questions')

    # ### end Alembic commands ###
