"""Added weaknesses to ai_analysis

Revision ID: 4d566f41ed26
Revises: 
Create Date: 2026-07-14 20:46:39.058144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d566f41ed26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weaknesses', sa.Text(), nullable=True))
        batch_op.alter_column('candidate_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.alter_column('candidate_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('weaknesses')

    # ### end Alembic commands ###
