"""Create settings table

Revision ID: 514b792d99c6
Revises: 2d8b16f44918
Create Date: 2026-07-29 00:53:45.385037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '514b792d99c6'
down_revision = '2d8b16f44918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('max_resume_size', sa.Integer(), nullable=True))
        batch_op.alter_column('company_name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('company_email',
               existing_type=mysql.VARCHAR(length=120),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('company_phone',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=20),
               nullable=True)
        batch_op.alter_column('company_address',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.drop_column('default_interview_duration')
        batch_op.drop_column('ai_score_threshold')
        batch_op.drop_column('company_website')
        batch_op.drop_column('auto_send_email')
        batch_op.drop_column('auto_generate_offer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_generate_offer', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('auto_send_email', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('company_website', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('ai_score_threshold', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('default_interview_duration', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('company_address',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('company_phone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('company_email',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('company_name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('max_resume_size')
        batch_op.drop_column('ai_model')

    # ### end Alembic commands ###
