"""add_resume_path_to_candidate

Revision ID: 7a695dd29b4c
Revises: 1fd27a8b7e55
Create Date: 2026-08-02 13:36:34.125686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a695dd29b4c'
down_revision = '1fd27a8b7e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_interview_results')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('resume_path')

    op.create_table('ai_interview_results',
    sa.Column('result_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('interview_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question', mysql.TEXT(), nullable=True),
    sa.Column('answer', mysql.TEXT(), nullable=True),
    sa.Column('ai_score', mysql.FLOAT(), nullable=True),
    sa.Column('feedback', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['ai_interviews.interview_id'], name=op.f('ai_interview_results_ibfk_1')),
    sa.PrimaryKeyConstraint('result_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
