"""Add job_id and meeting_link to interviews

Revision ID: 9d79dacb1e9b
Revises: 514b792d99c6
Create Date: 2026-07-31 19:52:59.625081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d79dacb1e9b'
down_revision = '514b792d99c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('meeting_link', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key(None, 'jobs', ['job_id'], ['job_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('meeting_link')
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
