"""Add scheduled date and time to AI interviews

Revision ID: add_scheduled_datetime
Revises: 76a1123db188
Create Date: 2026-08-04 10:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_scheduled_datetime'
down_revision = '76a1123db188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_interviews', sa.Column('scheduled_date', sa.Date(), nullable=True))
    op.add_column('ai_interviews', sa.Column('scheduled_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_interviews', 'scheduled_time')
    op.drop_column('ai_interviews', 'scheduled_date')
    # ### end Alembic commands ###
