"""Add ATS Analysis

Revision ID: b082a62780a9
Revises: 4c0a6ea2b409
Create Date: 2026-07-24 12:40:56.227210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b082a62780a9'
down_revision = '4c0a6ea2b409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ats_analysis',
    sa.Column('ats_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('ats_score', sa.Integer(), nullable=True),
    sa.Column('matched_keywords', sa.Text(), nullable=True),
    sa.Column('missing_keywords', sa.Text(), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('ats_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ats_analysis')
    # ### end Alembic commands ###
