"""Added users table

Revision ID: c6776c1971cd
Revises: 4d566f41ed26
Create Date: 2026-07-16 14:33:16.234180

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6776c1971cd'
down_revision = '4d566f41ed26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.alter_column('candidate_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_analysis', schema=None) as batch_op:
        batch_op.alter_column('candidate_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.drop_table('users')
    # ### end Alembic commands ###
