"""Add Chatbot History

Revision ID: d5f1c0b7f4c3
Revises: b9aac0b13139
Create Date: 2026-07-25 15:40:32.716358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5f1c0b7f4c3'
down_revision = 'b9aac0b13139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_history',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('user_question', sa.Text(), nullable=False),
    sa.Column('ai_answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.alter_column('candidate_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('job_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('questions',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.alter_column('questions',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('job_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('candidate_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.drop_table('chatbot_history')
    # ### end Alembic commands ###
