"""Add password to candidate

Revision ID: e172df5dba7e
Revises: d5f1c0b7f4c3
Create Date: 2026-07-25 16:31:02.246163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e172df5dba7e'
down_revision = 'd5f1c0b7f4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
